// backend/direct7.js
// Service d'envoi de SMS OTP via Direct7Networks + stockage Supabase
// WhatsApp pour préfixes non supportés par SMS (71, 75, etc.)
const axios = require('axios');

const DIRECT7_API_KEY = process.env.DIRECT7_API_KEY;
const DIRECT7_API_URL = process.env.D7_SMS_URL || 'https://api.d7networks.com/messages/v1/send';

const D7_OTP_PROVIDER_ENABLED = String(process.env.D7_OTP_PROVIDER_ENABLED || 'true').toLowerCase() === 'true';
const D7_OTP_PROVIDER_STRICT = String(process.env.D7_OTP_PROVIDER_STRICT || 'false').toLowerCase() === 'true';
const D7_OTP_SEND_URL = process.env.D7_OTP_SEND_URL || 'https://api.d7networks.com/verify/v1/otp/send-otp';
const D7_OTP_VERIFY_URL = process.env.D7_OTP_VERIFY_URL || 'https://api.d7networks.com/verify/v1/otp/verify-otp';
const D7_OTP_ORIGINATOR = process.env.D7_OTP_ORIGINATOR || 'VALIDEL';
const D7_OTP_TEMPLATE = process.env.D7_OTP_TEMPLATE || 'Votre code de verification VALIDEL est: {}. Il expire dans 5 minutes.';

function parsePositiveInt(value, fallback) {
  const parsed = Number.parseInt(String(value ?? ''), 10);
  return Number.isFinite(parsed) && parsed > 0 ? parsed : fallback;
}

const D7_OTP_EXPIRY_SECONDS = parsePositiveInt(process.env.D7_OTP_EXPIRY_SECONDS, 300);
const D7_OTP_RESEND_COOLDOWN_MS = parsePositiveInt(process.env.D7_OTP_RESEND_COOLDOWN_MS, 60 * 1000);

// In-memory OTP sessions keyed by normalized phone.
// mode=d7 -> store otpId generated by provider.
// mode=local -> fallback when provider fails, store generated code locally.
const otpSessions = new Map();

// Préfixes sénégalais dont le SMS est fiable via D7 (après +221)
const SMS_SUPPORTED_PREFIXES = ['70', '71', '75', '76', '77', '78'];

// Générer un code OTP à 4 chiffres
function generateOTP() {
  return Math.floor(1000 + Math.random() * 9000).toString();
}

function normalizePhoneForProvider(phone) {
  const digits = String(phone || '').replace(/\D/g, '');
  if (digits.startsWith('221')) return digits;
  if (digits.startsWith('0')) return `221${digits.substring(1)}`;
  if (digits.length === 9) return `221${digits}`;
  return digits;
}

function getOtpSessionKey(phone) {
  return normalizePhoneForProvider(phone);
}

function getAuthHeaders() {
  return {
    'Content-Type': 'application/json',
    Authorization: `Bearer ${DIRECT7_API_KEY}`,
  };
}

function extractOtpId(payload) {
  if (!payload || typeof payload !== 'object') return null;
  const candidates = [
    payload.otp_id,
    payload.otpId,
    payload.request_id,
    payload.requestId,
    payload.reference_id,
    payload.referenceId,
    payload.verification_id,
    payload.verificationId,
    payload.id,
    payload.data && payload.data.otp_id,
    payload.data && payload.data.otpId,
    payload.data && payload.data.request_id,
    payload.data && payload.data.requestId,
    payload.data && payload.data.reference_id,
    payload.data && payload.data.referenceId,
    payload.data && payload.data.verification_id,
    payload.data && payload.data.verificationId,
  ];

  for (const candidate of candidates) {
    if (candidate == null) continue;
    const text = String(candidate).trim();
    if (text.length > 0) return text;
  }
  return null;
}

function getStatusText(payload) {
  return String(
    payload?.status || payload?.verify_status || payload?.state || payload?.result || ''
  ).toLowerCase();
}

function isProviderVerificationSuccess(payload) {
  if (!payload || typeof payload !== 'object') return false;
  if (payload.valid === true || payload.success === true || payload.verified === true) return true;
  const status = getStatusText(payload);
  if (['success', 'successful', 'verified', 'approved', 'valid', 'ok'].includes(status)) return true;
  if (payload.data && typeof payload.data === 'object') return isProviderVerificationSuccess(payload.data);
  return false;
}

function isProviderVerificationFailure(payload) {
  if (!payload || typeof payload !== 'object') return false;
  if (payload.valid === false || payload.success === false || payload.verified === false) return true;
  const status = getStatusText(payload);
  if (['failed', 'failure', 'invalid', 'expired', 'denied', 'rejected', 'not_verified', 'error'].includes(status)) return true;
  const message = String(payload.message || payload.error || '').toLowerCase();
  if (/invalid|expired|incorrect|wrong|mismatch/.test(message)) return true;
  if (payload.data && typeof payload.data === 'object') return isProviderVerificationFailure(payload.data);
  return false;
}

function requireOtpProviderConfig() {
  if (!DIRECT7_API_KEY) {
    throw new Error('DIRECT7_API_KEY non configurée');
  }
  if (!D7_OTP_SEND_URL || !D7_OTP_VERIFY_URL) {
    throw new Error('D7_OTP endpoints non configurés');
  }
}

// Détermine si le numéro peut recevoir un SMS via D7
function canReceiveSMS(phone) {
  const match = phone.replace(/\D/g, '').match(/^221(\d{2})/);
  if (!match) return false;
  return SMS_SUPPORTED_PREFIXES.includes(match[1]);
}

// Envoyer un SMS via Direct7Networks
async function sendSMS(phone, message) {
  if (!DIRECT7_API_KEY) {
    throw new Error('DIRECT7_API_KEY non configurée');
  }

  // Formater le numéro (enlever le + pour l'API)
  const formattedPhone = phone.startsWith('+') ? phone.substring(1) : phone;

  try {
    const response = await axios.post(
      DIRECT7_API_URL,
      {
        messages: [
          {
            channel: 'sms',
            recipients: [formattedPhone],
            content: message,
            msg_type: 'text',
            data_coding: 'text'
          }
        ],
        message_globals: {
          originator: 'VALIDEL',
          report_url: null
        }
      },
      {
        headers: {
          ...getAuthHeaders()
        }
      }
    );

    console.log('[DIRECT7] SMS envoyé avec succès:', response.data);
    return { success: true, data: response.data };
  } catch (error) {
    const apiData = error?.response?.data;
    const detail = apiData?.detail;

    // Normaliser les erreurs Direct7 pour éviter "[object Object]"
    const detailCode = typeof detail === 'object' && detail ? detail.code : undefined;
    const detailMessage = typeof detail === 'object' && detail ? detail.message : undefined;
    const fallbackMessage = typeof apiData?.message === 'string' ? apiData.message : undefined;
    const finalMessage =
      (typeof detailMessage === 'string' && detailMessage.trim()) ||
      (typeof fallbackMessage === 'string' && fallbackMessage.trim()) ||
      (typeof error?.message === 'string' && error.message.trim()) ||
      "Erreur lors de l'envoi du SMS";

    console.error('[DIRECT7] Erreur envoi SMS:', apiData || error?.message || error);
    const prefix = detailCode ? `${detailCode}: ` : '';
    throw new Error(`${prefix}${finalMessage}`);
  }
}

// Envoyer un message WhatsApp via Direct7Networks
async function sendWhatsApp(phone, message) {
  if (!DIRECT7_API_KEY) {
    throw new Error('DIRECT7_API_KEY non configurée');
  }

  const formattedPhone = phone.startsWith('+') ? phone.substring(1) : phone;

  try {
    const response = await axios.post(
      DIRECT7_API_URL,
      {
        messages: [
          {
            channel: 'whatsapp',
            recipients: [formattedPhone],
            content: message,
            msg_type: 'text'
          }
        ],
        message_globals: {
          originator: 'VALIDEL',
          report_url: null
        }
      },
      {
        headers: {
          ...getAuthHeaders()
        }
      }
    );

    console.log('[DIRECT7] WhatsApp envoyé avec succès:', response.data);
    return { success: true, data: response.data };
  } catch (error) {
    const apiData = error?.response?.data;
    const detail = apiData?.detail;
    const detailMessage = typeof detail === 'object' && detail ? detail.message : undefined;
    const fallbackMessage = typeof apiData?.message === 'string' ? apiData.message : undefined;
    const finalMessage =
      (typeof detailMessage === 'string' && detailMessage.trim()) ||
      (typeof fallbackMessage === 'string' && fallbackMessage.trim()) ||
      (typeof error?.message === 'string' && error.message.trim()) ||
      "Erreur lors de l'envoi WhatsApp";

    console.error('[DIRECT7] Erreur envoi WhatsApp:', apiData || error?.message || error);
    throw new Error(finalMessage);
  }
}

async function sendProviderOTP(phone) {
  requireOtpProviderConfig();

  const recipient = normalizePhoneForProvider(phone);
  const response = await axios.post(
    D7_OTP_SEND_URL,
    {
      originator: D7_OTP_ORIGINATOR,
      recipient,
      content: D7_OTP_TEMPLATE,
      expiry: D7_OTP_EXPIRY_SECONDS,
      data_coding: 'text',
    },
    {
      headers: {
        ...getAuthHeaders(),
      },
    }
  );

  const otpId = extractOtpId(response.data);
  if (!otpId) {
    console.error('[OTP][D7] Réponse sans otp_id:', response.data);
    throw new Error('D7_OTP_ID_MISSING');
  }

  return { otpId, raw: response.data };
}

async function verifyProviderOTP(otpId, code) {
  requireOtpProviderConfig();

  const response = await axios.post(
    D7_OTP_VERIFY_URL,
    {
      otp_id: String(otpId),
      otp_code: String(code),
      otp: String(code),
    },
    {
      headers: {
        ...getAuthHeaders(),
      },
    }
  );

  const payload = response.data || {};
  if (isProviderVerificationSuccess(payload)) {
    return { valid: true };
  }
  if (isProviderVerificationFailure(payload)) {
    return { valid: false, error: 'Code OTP invalide ou expiré' };
  }

  console.warn('[OTP][D7] Réponse de vérification non reconnue:', payload);
  return { valid: false, error: 'Impossible de vérifier le code OTP' };
}

async function sendLocalFallbackOTP(phone) {
  const otp = generateOTP();
  const message = `Votre code de verification VALIDEL est: ${otp}. Il expire dans 5 minutes.`;
  const now = Date.now();
  const key = getOtpSessionKey(phone);

  if (canReceiveSMS(phone)) {
    await sendSMS(phone, message);
    console.log(`[OTP] Code envoyé à ${phone} via sms: ${otp}`);
    otpSessions.set(key, {
      mode: 'local',
      channel: 'sms',
      code: otp,
      expiresAt: now + (D7_OTP_EXPIRY_SECONDS * 1000),
      lastSentAt: now,
    });
    return { success: true, channel: 'sms', provider: 'local' };
  }

  await sendWhatsApp(phone, message);
  console.log(`[OTP] Code envoyé à ${phone} via whatsapp: ${otp}`);
  otpSessions.set(key, {
    mode: 'local',
    channel: 'whatsapp',
    code: otp,
    expiresAt: now + (D7_OTP_EXPIRY_SECONDS * 1000),
    lastSentAt: now,
  });
  return { success: true, channel: 'whatsapp', provider: 'local' };
}

// Envoyer un OTP et enregistrer une session vérifiable (D7 provider ou fallback local)
async function sendOTP(phone) {
  const now = Date.now();
  const key = getOtpSessionKey(phone);
  const existing = otpSessions.get(key);

  // Cost guard: if a valid OTP was already sent recently, do not send another one.
  if (existing && existing.expiresAt > now && (now - existing.lastSentAt) < D7_OTP_RESEND_COOLDOWN_MS) {
    return {
      success: true,
      channel: existing.channel || 'sms',
      reused: true,
      provider: existing.mode || 'local',
    };
  }

  if (D7_OTP_PROVIDER_ENABLED) {
    try {
      const sent = await sendProviderOTP(phone);
      otpSessions.set(key, {
        mode: 'd7',
        channel: 'sms',
        otpId: sent.otpId,
        expiresAt: now + (D7_OTP_EXPIRY_SECONDS * 1000),
        lastSentAt: now,
      });
      console.log(`[OTP][D7] OTP provider envoyé pour ${phone}, otp_id=${sent.otpId}`);
      return { success: true, channel: 'sms', provider: 'd7' };
    } catch (error) {
      console.error('[OTP][D7] Échec provider OTP:', error?.response?.data || error?.message || error);
      if (D7_OTP_PROVIDER_STRICT) {
        throw error;
      }
      console.warn('[OTP] Fallback local OTP activé');
      return sendLocalFallbackOTP(phone);
    }
  }

  return sendLocalFallbackOTP(phone);
}

// Vérifier un OTP
async function verifyOTP(phone, code) {
  const key = getOtpSessionKey(phone);
  const session = otpSessions.get(key);
  const now = Date.now();

  if (!session) {
    return { valid: false, error: 'OTP introuvable, demandez un nouveau code' };
  }

  if (!session.expiresAt || session.expiresAt <= now) {
    otpSessions.delete(key);
    return { valid: false, error: 'OTP expiré, demandez un nouveau code' };
  }

  if (session.mode === 'd7' && session.otpId) {
    try {
      const result = await verifyProviderOTP(session.otpId, code);
      if (result.valid) {
        otpSessions.delete(key);
      }
      return result;
    } catch (error) {
      console.error('[OTP][D7] Erreur vérification provider:', error?.response?.data || error?.message || error);
      if (D7_OTP_PROVIDER_STRICT) {
        throw new Error('Erreur fournisseur OTP');
      }
      return { valid: false, error: 'Impossible de vérifier le code OTP (provider)' };
    }
  }

  const valid = String(code || '') === String(session.code || '');
  if (valid) {
    otpSessions.delete(key);
    return { valid: true };
  }
  return { valid: false, error: 'Code OTP invalide' };
}

module.exports = {
  sendOTP,
  verifyOTP,
  sendSMS
};
