// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read Supabase configuration from Vite environment variables.
// Ensure you set `VITE_SUPABASE_URL` and `VITE_SUPABASE_KEY` in your `.env`.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fmhhdoqwslckisiofovx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_KEY || "";

if (!SUPABASE_PUBLISHABLE_KEY) {
  // At runtime this will appear in the console; during development make sure
  // to provide the VITE_SUPABASE_KEY. Keeping an empty key will cause
  // auth calls to fail with 400/401/500 depending on the Supabase project.
  // We avoid hardcoding a publishable key in source control.
  console.warn('VITE_SUPABASE_KEY is not set. Supabase auth may fail.');
}

export const supabase: SupabaseClient<Database> = SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: typeof window !== 'undefined' ? localStorage : undefined,
        persistSession: true,
        autoRefreshToken: true,
      }
    })
  : createClient<Database>(SUPABASE_URL, 'dummy-key');