// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read Supabase configuration from Vite environment variables.
// Ensure you set `VITE_SUPABASE_URL` and `VITE_SUPABASE_ANON_KEY` in your `.env`.
// (We also accept the legacy name `VITE_SUPABASE_KEY` as a fallback.)
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://fmhhdoqwslckisiofovx.supabase.co";
const SUPABASE_ANON_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_KEY ||
  "";

if (!SUPABASE_ANON_KEY) {
  // In dev, fail fast with a clear error instead of spamming 401s.
  const msg =
    'Supabase: clé manquante. Définissez VITE_SUPABASE_ANON_KEY dans le fichier .env (à la racine du projet). ' +
    'Utilisez la clé "anon" du projet Supabase (PAS la service_role).';
  if (import.meta.env.DEV) {
    throw new Error(msg);
  }
  console.warn(msg);
}

// INSPECT: supabase export
export const supabase: SupabaseClient<Database> = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined,
    persistSession: true,
    autoRefreshToken: true,
  }
});